version: "3"
services:
    web:
        build: .
        ports:
            - "8082:8082"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: ""
            ACCEPT_EULA: "Y"