version: "3"
networks:
  Hellsgate-net:
    driver: nat
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-Angular
    ports:
      - "4200:4200"
    restart: always
    # volumes:
    #   - ./HellsGate-AngularUis/src/app
    command: > 
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
    depends_on:
      - api
    networks:
      - Hellsgate-net
  api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-Api
    ports:
      - "8082:80"
    depends_on:
      - apidb
    networks:
      - Hellsgate-net
  apidb:
    ports:
      - "5432:5432"
    image: postgres
    restart: always
    environment:
      POSGRES_USER: "docker"
      POSTGRES_PASSWORD: "97531zzZ#"
      POSGRES_DB: "HellsGateDB"
    networks:
      - Hellsgate-net
