FROM node:12.9.0-alpine as builder
WORKDIR 'HellsGate-AngularUi/'
COPY package*.json ./
RUN npm ci
COPY . .
RUN npx ng build --prod HellsGate-AngularUi
FROM nginx
EXPOSE 80
COPY --from=builder /app/HellsGate-AngularUi /usr/share/nginx/html