version: "3"
networks:
  Hellsgate-net:
    driver: nat
services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    depends_on:
      - APIdb
    networks:
      - Hellsgate-net
  APIdb:
    ports:
      - "5432:5432"
    image: postgres
    restart: always
    environment:
      POSGRES_USER: "docker"
      POSTGRES_PASSWORD: "97531zzZ#"
      POSGRES_DB: "HellsGateDB"
    networks:
      - Hellsgate-net
