version: "3"
services:
    web:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8082:8082"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        container_name: db-server
        environment:
            SA_PASSWORD: "97531zzZ#"
            ACCEPT_EULA: "Y"