name: .NET Core

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore
    - name: Build with dotnet
      run: dotnet build --configuration Release HellsGate.sln
    - name: Test     
      run: dotnet test HellsGate.sln
    - name: Publish
      run: dotnet publish